// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: {
	medicalMarket: string | null;
	medicAuthority: string | null;
	multisig: { ss58: string; h160: string; threshold: number; signatories: string[] } | null;
} = {
	medicalMarket: "0x3ed62137c5db927cb137c26455969116bf0c23cb",
	medicAuthority: "0x962c0940d72e7db6c9a5f81f1ca87d8db2b82a23",
	multisig: {
		ss58: "5Drae25fn2KwZKuST7LCvB7D4rdyqFoMAdSD4CEdQPuQr2Lk",
		h160: "0x1597f37473220526382eb1a190a4fd97e7270648",
		threshold: 2,
		signatories: [
			"5Doa63xYuFXQaWkM5decEj7cgrr5eCcP5YbN4faTHvWdRdQs",
			"5HaLFkCjJyuUSnyoPKYukWksCKvy489QmiTKCiJUxoorpHvq",
			"5Hp3SxTNMvussku1zRRaFwn7waW4uHdhJUF61st9EZzXb8wd",
		],
	},
};
