import * as fs from "fs";
import * as path from "path";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

export type NetworkPreset = "local" | "paseo";

export type NetworkDeployment = {
	medicalMarket: string | null;
	medicAuthority: string | null;
	multisig: {
		ss58: string;
		h160: string;
		threshold: number;
		signatories: string[];
	} | null;
};

export type DeploymentsShape = Record<NetworkPreset, NetworkDeployment>;

const EMPTY_NETWORK: NetworkDeployment = {
	medicalMarket: null,
	medicAuthority: null,
	multisig: null,
};

const EMPTY: DeploymentsShape = {
	local: { ...EMPTY_NETWORK },
	paseo: { ...EMPTY_NETWORK },
};

function readAll(): DeploymentsShape {
	try {
		const raw = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8")) as Partial<
			Record<NetworkPreset, Partial<NetworkDeployment>>
		>;
		return {
			local: { ...EMPTY_NETWORK, ...(raw.local ?? {}) },
			paseo: { ...EMPTY_NETWORK, ...(raw.paseo ?? {}) },
		};
	} catch {
		return { local: { ...EMPTY_NETWORK }, paseo: { ...EMPTY_NETWORK } };
	}
}

export function readDeployments(network: NetworkPreset): NetworkDeployment {
	return readAll()[network];
}

export function updateDeployments(
	network: NetworkPreset,
	updates: Partial<NetworkDeployment>,
): void {
	const all = readAll();
	all[network] = { ...all[network], ...updates };

	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(all, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const fmtMultisig = (v: NetworkDeployment["multisig"]) => {
		if (v === null) return "null";
		const sigs = v.signatories.map((s) => `\t\t\t\t"${s}"`).join(",\n");
		return `{
\t\t\tss58: "${v.ss58}",
\t\t\th160: "${v.h160}",
\t\t\tthreshold: ${v.threshold},
\t\t\tsignatories: [
${sigs},
\t\t\t],
\t\t}`;
	};

	const fmtNetwork = (n: NetworkDeployment) =>
		`{
\t\tmedicalMarket: ${fmt(n.medicalMarket)},
\t\tmedicAuthority: ${fmt(n.medicAuthority)},
\t\tmultisig: ${fmtMultisig(n.multisig)},
\t}`;

	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export type NetworkPreset = "local" | "paseo";

export type NetworkDeployment = {
\tmedicalMarket: string | null;
\tmedicAuthority: string | null;
\tmultisig: { ss58: string; h160: string; threshold: number; signatories: string[] } | null;
};

export const deployments: Record<NetworkPreset, NetworkDeployment> = {
\tlocal: ${fmtNetwork(all.local)},
\tpaseo: ${fmtNetwork(all.paseo)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

export function inferNetworkFromRpc(rpc: string): NetworkPreset {
	return /127\.0\.0\.1|localhost/.test(rpc) ? "local" : "paseo";
}
