import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

function updateDeployments(key: string, address: string) {
	let data: Record<string, string | null> = { evm: null, pvm: null, medicalMarket: null };
	try {
		data = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8"));
	} catch {
		// File doesn't exist yet
	}
	data[key] = address;

	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: { evm: string | null; pvm: string | null; medicalMarket: string | null } = {
\tevm: ${fmt(data.evm ?? null)},
\tpvm: ${fmt(data.pvm ?? null)},
\tmedicalMarket: ${fmt(data.medicalMarket ?? null)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	console.log("Deploying MedicalMarket (PVM/resolc)...");

	const [walletClient] = await hre.viem.getWalletClients();
	const publicClient = await hre.viem.getPublicClient();
	const artifact = await hre.artifacts.readArtifact("MedicalMarket");

	const hash = await walletClient.deployContract({
		abi: artifact.abi,
		bytecode: artifact.bytecode as `0x${string}`,
	});

	const receipt = await publicClient.waitForTransactionReceipt({
		hash,
		timeout: 120_000,
	});

	if (!receipt.contractAddress) {
		throw new Error(`Deploy tx ${hash} did not create a contract`);
	}

	console.log(`MedicalMarket deployed to: ${receipt.contractAddress}`);
	updateDeployments("medicalMarket", receipt.contractAddress);
	console.log("Updated deployments.json and web/src/config/deployments.ts");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
